const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const BaseIntegration = require('../../lib/integrations/base-integration');

// Concrete subclass for testing
class TestIntegration extends BaseIntegration {
  constructor() {
    super();
    this.name = 'test';
    this.displayName = 'Test Platform';
    this.generatedFiles = ['test-generated.md'];
    this.bridgeFiles = ['TEST_BRIDGE.md'];
    this.platformDir = '.test-platform';
  }

  async generateFiles() {
    await this.writeGeneratedFile('test-generated.md', '# Generated');
    await this.writeBridgeFile('TEST_BRIDGE.md', '# Bridge Content');
  }
}

describe('BaseIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-test-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. cannot instantiate BaseIntegration directly', () => {
    expect(() => new BaseIntegration()).toThrow('abstract');
  });

  test('2. install creates platform directory and calls generateFiles', async () => {
    const integration = new TestIntegration();
    await integration.install();

    expect(await fs.pathExists('.test-platform')).toBe(true);
    expect(await fs.pathExists('test-generated.md')).toBe(true);
    expect(await fs.pathExists('TEST_BRIDGE.md')).toBe(true);
  });

  test('3. validate returns valid when all files exist', async () => {
    const integration = new TestIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('test-generated.md');
    expect(result.present).toContain('TEST_BRIDGE.md');
    expect(result.missing).toHaveLength(0);
  });

  test('4. validate returns invalid when files are missing', async () => {
    const integration = new TestIntegration();
    const result = await integration.validate();

    expect(result.valid).toBe(false);
    expect(result.missing).toContain('test-generated.md');
    expect(result.missing).toContain('TEST_BRIDGE.md');
  });

  test('5. writeBridgeFile creates new file with markers', async () => {
    const integration = new TestIntegration();
    await integration.writeBridgeFile('bridge.md', 'Hello World');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain(
      '<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->'
    );
    expect(content).toContain('Hello World');
    expect(content).toContain('<!-- End ContextKit -->');
  });

  test('6. writeBridgeFile replaces marked section in existing file', async () => {
    const integration = new TestIntegration();

    // Create initial file with markers
    await integration.writeBridgeFile('bridge.md', 'Version 1');
    // Replace with new content
    await integration.writeBridgeFile('bridge.md', 'Version 2');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain('Version 2');
    expect(content).not.toContain('Version 1');
    // Should only have one set of markers
    expect(
      content.split(
        '<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->'
      ).length
    ).toBe(2);
  });

  test('7. writeBridgeFile appends to existing file without markers', async () => {
    const integration = new TestIntegration();

    // Create manual file without markers
    await fs.writeFile('bridge.md', '# My Custom Content\n\nThis is user content.\n');
    // Append contextkit section
    await integration.writeBridgeFile('bridge.md', 'ContextKit Section');

    const content = await fs.readFile('bridge.md', 'utf-8');
    expect(content).toContain('# My Custom Content');
    expect(content).toContain('This is user content.');
    expect(content).toContain('ContextKit Section');
    expect(content).toContain(
      '<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->'
    );
  });

  test('8. isUpToDate returns false when generated files are missing', async () => {
    const integration = new TestIntegration();
    // No files written yet
    const result = await integration.isUpToDate();
    expect(result).toBe(false);
  });

  test('9. isUpToDate returns false when bridge file version does not match package', async () => {
    const integration = new TestIntegration();
    await integration.install(true); // force full generation

    // Tamper with the version in the bridge file
    const content = await fs.readFile('TEST_BRIDGE.md', 'utf-8');
    await fs.writeFile('TEST_BRIDGE.md', content.replace(/Version: [0-9.]+/, 'Version: 0.0.1'));

    const result = await integration.isUpToDate();
    expect(result).toBe(false);
  });

  test('10. isUpToDate returns false when bridge file has no Version: tag', async () => {
    const integration = new TestIntegration();
    await integration.install(true); // writes bridge file without Version: tag

    // TestIntegration bridge content is '# Bridge Content' — no Version: tag
    // version regex match is null → returns false
    const result = await integration.isUpToDate();
    expect(result).toBe(false);
  });

  test('11. install skips generateFiles when already up to date', async () => {
    class NoVersionBridgeIntegration extends BaseIntegration {
      constructor() {
        super();
        this.name = 'no-version';
        this.displayName = 'No Version';
        this.generatedFiles = ['nv-generated.md'];
        this.bridgeFiles = [];
        this.platformDir = null;
      }
      async generateFiles() {
        await this.writeGeneratedFile('nv-generated.md', '# Generated');
      }
    }

    const integration = new NoVersionBridgeIntegration();
    // First install
    await integration.install(true);

    // Spy on generateFiles
    const spy = jest.spyOn(integration, 'generateFiles');
    // Second install without force — should be up to date (no bridge file to check version)
    await integration.install(false);

    // No bridge file = version check skipped, all files present = up to date
    expect(spy).not.toHaveBeenCalled();
  });

  test('12. install with force=true always calls generateFiles', async () => {
    const integration = new TestIntegration();
    await integration.install(true); // first install

    const spy = jest.spyOn(integration, 'generateFiles');
    await integration.install(true); // force re-run

    expect(spy).toHaveBeenCalled();
  });

  test('13. getStandardsBlock returns standards reference markdown', () => {
    const integration = new TestIntegration();
    const block = integration.getStandardsBlock();

    expect(block).toContain('.contextkit/standards/code-style.md');
    expect(block).toContain('.contextkit/standards/testing.md');
    expect(block).toContain('.contextkit/standards/architecture.md');
    expect(block).toContain('.contextkit/commands/analyze.md');
    expect(block).toContain('.contextkit/product/mission-lite.md');
  });

  test('14. ClaudeIntegration isUpToDate returns false when CLAUDE.md has old version', async () => {
    const ClaudeIntegration = require('../../lib/integrations/claude-integration');
    const integration = new ClaudeIntegration();
    await integration.install(true);

    // Tamper with version in CLAUDE.md
    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    const tampered = content.replace(/Version: [0-9.]+/, 'Version: 0.0.1');
    await fs.writeFile('CLAUDE.md', tampered);

    const result = await integration.isUpToDate();
    expect(result).toBe(false);
  });

  test('15. ClaudeIntegration install skips when version matches and all files present', async () => {
    const ClaudeIntegration = require('../../lib/integrations/claude-integration');
    const integration = new ClaudeIntegration();
    await integration.install(true); // first install with correct version

    const spy = jest.spyOn(integration, 'generateFiles');
    await integration.install(false); // second call — up to date

    expect(spy).not.toHaveBeenCalled();
  });
});
