const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const ClaudeIntegration = require('../../lib/integrations/claude-integration');

describe('ClaudeIntegration', () => {
  let tempDir;
  let originalCwd;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'contextkit-claude-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tempDir);
  });

  test('1. creates CLAUDE.md bridge file', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    expect(await fs.pathExists('CLAUDE.md')).toBe(true);
    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain(
      '<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->'
    );
    expect(content).toContain('Project Standards');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('2. creates .claude/rules/contextkit-standards.md with alwaysApply', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-standards.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('alwaysApply: true');
    expect(content).toContain('auto-loaded via CLAUDE.md imports');
    expect(content).toContain('Code style conventions (from code-style.md)');
  });

  test('3. creates .claude/rules/contextkit-testing.md with test file globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-testing.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('**/*.test.*');
    expect(content).toContain('**/*.spec.*');
    expect(content).toContain('numbered');
  });

  test('4. creates .claude/rules/contextkit-code-style.md with source globs', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const filePath = '.claude/rules/contextkit-code-style.md';
    expect(await fs.pathExists(filePath)).toBe(true);
    const content = await fs.readFile(filePath, 'utf-8');
    expect(content).toContain('src/**');
    expect(content).toContain('lib/**');
  });

  test('5. creates all skills as .claude/skills/<name>/SKILL.md with frontmatter', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const allSkills = [
      'analyze',
      'review',
      'fix',
      'refactor',
      'test',
      'doc',
      'spec',
      'ck',
      'squad',
      'squad-architect',
      'squad-dev',
      'squad-test',
      'squad-review',
      'squad-auto',
      'squad-auto-parallel',
      'squad-reset',
      'squad-doc',
      'doc-arch',
      'doc-feature',
      'doc-component',
      'agent-push-checklist',
      'context-budget',
      'standards-aware',
    ];
    for (const skill of allSkills) {
      const filePath = `.claude/skills/${skill}/SKILL.md`;
      expect(await fs.pathExists(filePath)).toBe(true);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('description:');
      expect(content).toContain('allowed-tools:');
      expect(content).toContain('.contextkit/commands/');
    }
  });

  test('10. creates agent skills referencing agents/ subdir', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const agentSkills = ['agent-push-checklist', 'context-budget', 'standards-aware'];
    for (const skill of agentSkills) {
      const filePath = `.claude/skills/${skill}/SKILL.md`;
      expect(await fs.pathExists(filePath)).toBe(true);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('.contextkit/commands/agents/');
    }
  });

  test('11. squad-auto and squad-auto-parallel skills have context: fork', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    for (const skill of ['squad-auto', 'squad-auto-parallel']) {
      const content = await fs.readFile(`.claude/skills/${skill}/SKILL.md`, 'utf-8');
      expect(content).toContain('context: fork');
    }
  });

  test('12. removes legacy .claude/commands/ files on install', async () => {
    // Pre-create legacy command files to simulate an existing user's setup
    await fs.ensureDir('.claude/commands');
    await fs.writeFile('.claude/commands/analyze.md', 'legacy content');
    await fs.writeFile('.claude/commands/squad-auto.md', 'legacy content');

    const integration = new ClaudeIntegration();
    await integration.install();

    expect(await fs.pathExists('.claude/commands/analyze.md')).toBe(false);
    expect(await fs.pathExists('.claude/commands/squad-auto.md')).toBe(false);
  });

  test('6. appends to existing CLAUDE.md without overwriting', async () => {
    // Create a manual CLAUDE.md
    await fs.writeFile('CLAUDE.md', '# My Custom Claude Config\n\nCustom rules here.\n');

    const integration = new ClaudeIntegration();
    await integration.install();

    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain('# My Custom Claude Config');
    expect(content).toContain('Custom rules here.');
    expect(content).toContain(
      '<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->'
    );
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  test('7. validate returns valid after install', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.missing).toHaveLength(0);
  });

  test('8. validate returns invalid before install', async () => {
    const integration = new ClaudeIntegration();
    const result = await integration.validate();

    expect(result.valid).toBe(false);
    expect(result.missing.length).toBeGreaterThan(0);
  });

  test('9. CLAUDE.md includes ContextKit version stamp matching package.json', async () => {
    const integration = new ClaudeIntegration();
    await integration.install();

    const { version } = require('../../package.json');
    const content = await fs.readFile('CLAUDE.md', 'utf-8');
    expect(content).toContain(`Version: ${version}`);
  });
});
