const fs = require('fs-extra');
const path = require('path');
const os = require('os');

const OpencodeIntegration = require('../../lib/integrations/opencode-integration');

describe('OpencodeIntegration', () => {
  let tmpDir;
  let originalCwd;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ck-opencode-'));
    originalCwd = process.cwd();
    process.chdir(tmpDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.remove(tmpDir);
  });

  it('1. creates AGENTS.md bridge file', async () => {
    const integration = new OpencodeIntegration();
    await integration.install();

    expect(await fs.pathExists('AGENTS.md')).toBe(true);
    const content = await fs.readFile('AGENTS.md', 'utf-8');
    expect(content).toContain('<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->');
    expect(content).toContain('.contextkit/standards/code-style.md');
  });

  it('2. does not create .opencode/ directory', async () => {
    const integration = new OpencodeIntegration();
    await integration.install();

    expect(await fs.pathExists('.opencode')).toBe(false);
  });

  it('3. appends to existing AGENTS.md without overwriting custom content', async () => {
    await fs.writeFile('AGENTS.md', '# My Agents Config\n\nCustom content.\n');

    const integration = new OpencodeIntegration();
    await integration.install();

    const content = await fs.readFile('AGENTS.md', 'utf-8');
    expect(content).toContain('# My Agents Config');
    expect(content).toContain('Custom content.');
    expect(content).toContain('<!-- Generated by ContextKit (@nolrm/contextkit) https://www.npmjs.com/package/@nolrm/contextkit -->');
  });

  it('4. validate returns valid after install', async () => {
    const integration = new OpencodeIntegration();
    await integration.install();

    const result = await integration.validate();
    expect(result.valid).toBe(true);
    expect(result.present).toContain('AGENTS.md');
  });
});
